spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          eh-college-client:
            provider: eh-college-provider
            client-id: eh-college-client
            client-secret: eh-college-secret
            authorization-grant-type: client_credentials
            scope: read
        provider:
          eh-college-provider:
            token-uri: http://localhost:9000/oauth2/token
